require:
    - 'source-map-support/register'
    - 'ts-node/register'
spec: './src/**/*.spec.ts'
node-option:
    - 'experimental-specifier-resolution=node'
    - 'loader=ts-node/esm'
# Set to 0 to disable timeout when debugging.
timeout: 20000
watch-files: './src/**/*.ts'
