name: size

on:
  pull_request:
    branches:
    - master

jobs:
  size:
    name: Size Check
    runs-on: ubuntu-latest
    env:
      CI: true
      CI_JOB_NUMBER: 1
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Check bundle sizes
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: pnpm size-limit --json
          package_manager: pnpm
